### ISSUE TITLE
Spring Rest Docs와 Swagger 연동을 위한 OpenAPI3 생성

### ISSUE THREAD

**Issue by yudonggeun** [kSideProject/kpring#16]
## :x: 문제점
Spring Rest Docs를 사용하면 생성된 snippet을 사용하여 asciidoc 문서를 API 마다 생성해주어야 합니다. 
또한 API를 테스트할 때, 요청을 직접 만들어야 하는 귀찮은 반복 작업이 존재합니다.

### 1. OpenAPI3 자동생성
https://github.com/ePages-de/restdocs-api-spec?tab=readme-ov-file#webtestclient-based-tests
해당 오픈 소스를 통해서 Spring Rest Docs의 코드를 OpenAPI 형식으로 자동으로 변환시킬 수 있습니다.

우선 해당 라이브러리를 사용하기 위한 모듈을 가져옵니다.
```
// open api3
implementation("com.epages:restdocs-api-spec-mockmvc:0.19.2")
implementation("com.epages:restdocs-api-spec-webtestclient:0.19.2")
```

이를 위해서 spring rest docs를 생성하는 `test` 모듈의 코드를 수정하였습니다.
![image](https://github.com/kSideProject/kpring/assets/67232422/948badd3-3cc6-45fd-95e0-9fc29cc90b42)
해당 코드의 변경사항은 WebTestclientDocument.document() 에서 WebTestClientDocumentWapper.document()를 사용하여 문서 생성을 위한 Wapper를 사용한 것입니다.

### 2. SwaggerUI 서버 가동
gradle에서 openapi3 task를 실행해서 생성된 파일을 swagger 서버가 사용하도록 환경을 구성하였습니다.
```yml
# docker compose file
services:
  swagger-server:
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8080"
    volumes:
      - "./build/api-spec/openapi3.yaml:/usr/share/nginx/html/openapi.yaml" # 생성된 openapi3 바인드
    environment:
      URL: ./openapi.yaml # 볼륨에 존재하는 openapi3.yaml 접근을 위한 localhost url
```
생성된 api 문서를 swagger를 통해서 쉽게 요청을 생성할 수 있습니다.
![image](https://github.com/kSideProject/kpring/assets/67232422/0cef788e-d89a-4446-8d03-21898b681c51)

## 🔗 관련 문서 
#10 #11
[swaggerUI 설정 문서](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md)
[spring rest docs 연동 오픈소스](https://github.com/ePages-de/restdocs-api-spec?tab=readme-ov-file#webtestclient-based-tests)
